name: Deploy to Azure Static Web App
on:
    push: # Trigger workflow on code push
        branches:
        - main # Only run workflow on the main branch
        jobs:
            build-and-deploy:
            runs-on: ubuntu-latest # Use the latest Ubuntu environment
            steps:
                - name: Checkout Code
                uses: actions/checkout@v3 # Step 1: Check out the repository code
                - name: Deploy to Azure Static Web App
                uses: Azure/static-web-apps-deploy@v1 # Step 2: Use Azure Static Web App deployment action
                    with:
                        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
                            app_location: "/" # Root directory for static files
                            api_location: "" # No API backend
                            output_location: "" # No build output
                            deployment_action: "upload" # Add deployment action to resolve the error